/**
 * WKQUIZ QUESTION BANK INDEX
 * Auto-generated by scripts/build.js
 * Total Active Questions in Git Repository: 2285
 * Questions are fetched on demand from: https://cdn.jsdelivr.net/gh/soulinmotionn-source/wkquizgit@main/question-bank/
 */

const WKQUIZ_INDEX = {
  "version": "2.0.0",
  "generatedAt": "2026-09-03T06:10:38.700Z",
  "totalQuestions": 2285,
  "categories": {
    "anatomy-physiology": {
      "total": 117,
      "easy": 40,
      "medium": 39,
      "hard": 38
    },
    "automotive": {
      "total": 12,
      "easy": 4,
      "medium": 4,
      "hard": 4
    },
    "celebrity": {
      "total": 11,
      "easy": 4,
      "medium": 4,
      "hard": 3
    },
    "computers": {
      "total": 13,
      "easy": 5,
      "medium": 4,
      "hard": 4
    },
    "diseases-disorders": {
      "total": 115,
      "easy": 39,
      "medium": 38,
      "hard": 38
    },
    "drama": {
      "total": 109,
      "easy": 38,
      "medium": 35,
      "hard": 36
    },
    "electrical-symbols-items": {
      "total": 115,
      "easy": 39,
      "medium": 38,
      "hard": 38
    },
    "electrical": {
      "total": 119,
      "easy": 42,
      "medium": 38,
      "hard": 39
    },
    "electronics": {
      "total": 106,
      "easy": 36,
      "medium": 34,
      "hard": 36
    },
    "engineering": {
      "total": 108,
      "easy": 37,
      "medium": 35,
      "hard": 36
    },
    "english": {
      "total": 12,
      "easy": 4,
      "medium": 4,
      "hard": 4
    },
    "entertainment": {
      "total": 111,
      "easy": 38,
      "medium": 37,
      "hard": 36
    },
    "general-knowledge": {
      "total": 111,
      "easy": 38,
      "medium": 37,
      "hard": 36
    },
    "geography": {
      "total": 14,
      "easy": 5,
      "medium": 5,
      "hard": 4
    },
    "history": {
      "total": 14,
      "easy": 5,
      "medium": 5,
      "hard": 4
    },
    "hvac": {
      "total": 122,
      "easy": 42,
      "medium": 41,
      "hard": 39
    },
    "iq-logic": {
      "total": 14,
      "easy": 5,
      "medium": 5,
      "hard": 4
    },
    "mathematics": {
      "total": 14,
      "easy": 5,
      "medium": 5,
      "hard": 4
    },
    "medical-terminology": {
      "total": 117,
      "easy": 40,
      "medium": 39,
      "hard": 38
    },
    "medical": {
      "total": 115,
      "easy": 39,
      "medium": 38,
      "hard": 38
    },
    "movies": {
      "total": 111,
      "easy": 38,
      "medium": 37,
      "hard": 36
    },
    "music": {
      "total": 12,
      "easy": 4,
      "medium": 4,
      "hard": 4
    },
    "nclex": {
      "total": 122,
      "easy": 44,
      "medium": 38,
      "hard": 40
    },
    "nursing": {
      "total": 123,
      "easy": 43,
      "medium": 41,
      "hard": 39
    },
    "pharmacology": {
      "total": 117,
      "easy": 40,
      "medium": 39,
      "hard": 38
    },
    "science": {
      "total": 108,
      "easy": 38,
      "medium": 34,
      "hard": 36
    },
    "technology": {
      "total": 112,
      "easy": 38,
      "medium": 37,
      "hard": 37
    },
    "tv-shows": {
      "total": 111,
      "easy": 38,
      "medium": 37,
      "hard": 36
    }
  }
};
const WKQUIZ_QUESTIONS = []; // Questions maintained in Git repository question-bank/*.json

if (typeof module !== "undefined" && module.exports) {
  module.exports = { WKQUIZ_INDEX, WKQUIZ_QUESTIONS };
}
if (typeof window !== "undefined") {
  window.WKQUIZ_INDEX = WKQUIZ_INDEX;
  window.WKQUIZ_QUESTIONS = WKQUIZ_QUESTIONS;
}
