/**
 * WKQUIZ QUESTION BANK INDEX
 * Auto-generated by scripts/build.js
 * Total Active Questions in Git Repository: 2516
 * Questions are fetched on demand from: https://cdn.jsdelivr.net/gh/soulinmotionn-source/wkquizgit@main/question-bank/
 */

const WKQUIZ_INDEX = {
  "version": "2.0.0",
  "generatedAt": "2026-09-03T10:13:06.787Z",
  "totalQuestions": 2516,
  "categories": {
    "anatomy-physiology": {
      "total": 125,
      "easy": 43,
      "medium": 42,
      "hard": 40
    },
    "automotive": {
      "total": 20,
      "easy": 7,
      "medium": 7,
      "hard": 6
    },
    "celebrity": {
      "total": 19,
      "easy": 7,
      "medium": 7,
      "hard": 5
    },
    "computers": {
      "total": 21,
      "easy": 8,
      "medium": 7,
      "hard": 6
    },
    "diseases-disorders": {
      "total": 123,
      "easy": 42,
      "medium": 41,
      "hard": 40
    },
    "drama": {
      "total": 117,
      "easy": 41,
      "medium": 38,
      "hard": 38
    },
    "electrical-symbols-items": {
      "total": 123,
      "easy": 42,
      "medium": 41,
      "hard": 40
    },
    "electrical": {
      "total": 127,
      "easy": 45,
      "medium": 41,
      "hard": 41
    },
    "electronics": {
      "total": 114,
      "easy": 39,
      "medium": 37,
      "hard": 38
    },
    "engineering": {
      "total": 116,
      "easy": 40,
      "medium": 38,
      "hard": 38
    },
    "english": {
      "total": 20,
      "easy": 7,
      "medium": 7,
      "hard": 6
    },
    "entertainment": {
      "total": 119,
      "easy": 41,
      "medium": 40,
      "hard": 38
    },
    "general-knowledge": {
      "total": 119,
      "easy": 41,
      "medium": 40,
      "hard": 38
    },
    "geography": {
      "total": 22,
      "easy": 8,
      "medium": 8,
      "hard": 6
    },
    "history": {
      "total": 21,
      "easy": 7,
      "medium": 8,
      "hard": 6
    },
    "hvac": {
      "total": 130,
      "easy": 45,
      "medium": 44,
      "hard": 41
    },
    "iq-logic": {
      "total": 22,
      "easy": 8,
      "medium": 8,
      "hard": 6
    },
    "mathematics": {
      "total": 22,
      "easy": 8,
      "medium": 8,
      "hard": 6
    },
    "medical-terminology": {
      "total": 125,
      "easy": 43,
      "medium": 42,
      "hard": 40
    },
    "medical": {
      "total": 123,
      "easy": 42,
      "medium": 41,
      "hard": 40
    },
    "mixed-quiz": {
      "total": 8,
      "easy": 3,
      "medium": 3,
      "hard": 2
    },
    "movies": {
      "total": 119,
      "easy": 41,
      "medium": 40,
      "hard": 38
    },
    "music": {
      "total": 20,
      "easy": 7,
      "medium": 7,
      "hard": 6
    },
    "nclex": {
      "total": 130,
      "easy": 47,
      "medium": 41,
      "hard": 42
    },
    "nursing": {
      "total": 131,
      "easy": 46,
      "medium": 44,
      "hard": 41
    },
    "pharmacology": {
      "total": 125,
      "easy": 43,
      "medium": 42,
      "hard": 40
    },
    "science": {
      "total": 116,
      "easy": 41,
      "medium": 37,
      "hard": 38
    },
    "technology": {
      "total": 120,
      "easy": 41,
      "medium": 40,
      "hard": 39
    },
    "tv-shows": {
      "total": 119,
      "easy": 41,
      "medium": 40,
      "hard": 38
    }
  }
};
const WKQUIZ_QUESTIONS = []; // Questions maintained in Git repository question-bank/*.json

if (typeof module !== "undefined" && module.exports) {
  module.exports = { WKQUIZ_INDEX, WKQUIZ_QUESTIONS };
}
if (typeof window !== "undefined") {
  window.WKQUIZ_INDEX = WKQUIZ_INDEX;
  window.WKQUIZ_QUESTIONS = WKQUIZ_QUESTIONS;
}
